### PR TITLE
Don't package non-node functions (fix for #644)

### LINKED ISSUE #644: Error with multiple runtimes
# This is a Bug Report 

## Description

If you try to add a second runtime (in my example golang) for a new Lambda, you get following error:
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
in
node_modules/serverless-webpack/lib/validate.js:199:36
because the plugin tries to use the golang lambda to do webpack stuff.

If you just filter the functions for runtimes starting with node fixes the problem.
```javascript
//  Lookup associated Serverless functions
        const allEntryFunctions = _.map(
          this.serverless.service.getAllFunctions().map(
            funcName =>this.serverless.service.getFunction(funcName) )
            .filter(func => func.runtime.startsWith('node')), func => {
          const handler = func.handler;
          const handlerFile = path.relative('.', getHandlerFile(handler));
          const runtime = func.runtime
          return {
            handlerFile,
            funcName: func.name,
            func,
          };
        });
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.5
* ***Webpack version you're using***: 4.44.2
* ***Serverless Framework Version you're using***: 2.4.0
* ***Operating System***: Windows 10 WSL, so I guess linux?
* ***Stack Trace (if available)***:
 Type Error ---------------------------------------------
 
  TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
      at validateString (internal/validators.js:120:11)
      at Object.relative (path.js:1054:5)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless-webpack/lib/validate.js:199:36
      at arrayMap (/home/dennis/go/src/sportsplaner/node_modules/lodash/lodash.js:639:23)
      at Function.map (/home/dennis/go/src/sportsplaner/node_modules/lodash/lodash.js:9580:14)
      at processConfig (/home/dennis/go/src/sportsplaner/node_modules/serverless-webpack/lib/validate.js:196:37)
      at ServerlessWebpack.validate (/home/dennis/go/src/sportsplaner/node_modules/serverless-webpack/lib/validate.js:245:14)
  From previous event:
      at Object.webpack:validate:validate [as hook] (/home/dennis/go/src/sportsplaner/node_modules/serverless-webpack/index.js:152:63)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:510:55
  From previous event:
      at PluginManager.invoke (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:510:22)
      at PluginManager.spawn (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:530:17)
      at ServerlessWebpack.<anonymous> (/home/dennis/go/src/sportsplaner/node_modules/serverless-webpack/index.js:93:53)
  From previous event:
      at Object.before:package:createDeploymentArtifacts [as hook] (/home/dennis/go/src/sportsplaner/node_modules/serverless-webpack/index.js:93:12)
  From previous event:
      at PluginManager.invoke (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:510:22)
      at PluginManager.spawn (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:530:17)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50
  From previous event:
      at Object.before:deploy:deploy [as hook] (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/plugins/deploy/deploy.js:102:22)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:510:55
  From previous event:
      at PluginManager.invoke (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:510:22)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:545:24
  From previous event:
      at PluginManager.run (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/classes/PluginManager.js:545:8)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless/lib/Serverless.js:168:33
  From previous event:
      at Serverless.run (/home/dennis/go/src/sportsplaner/node_modules/serverless/lib/Serverless.js:155:74)
      at /home/dennis/go/src/sportsplaner/node_modules/serverless/scripts/serverless.js:50:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/home/dennis/go/src/sportsplaner/node_modules/serverless/scripts/serverless.js:50:4)
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
      at Module.load (internal/modules/cjs/loader.js:986:32)
      at Function.Module._load (internal/modules/cjs/loader.js:879:14)
      at Module.require (internal/modules/cjs/loader.js:1026:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/home/dennis/go/src/sportsplaner/node_modules/serverless/bin/serverless.js:47:1)
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
      at Module.load (internal/modules/cjs/loader.js:986:32)
      at Function.Module._load (internal/modules/cjs/loader.js:879:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at /home/dennis/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.17.0
     Framework Version:         2.4.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1

### PR DESCRIPTION
**Pull request by jgrantr**
## What did you implement:

Most of serverless-webpack already deals with not packaging non-node functions. There is only one section that is still problematic. This fix deals with the issue where a runtime may be defined for an individual function or for a provider. It will default to a runtime of "nodejs" if no runtime is specified at either the function or provider level.

Closes #644 

## How did you implement it:

When processing the async config, implemented an extra step before mapping the functions to filter out functions that don't have a node runtime.

## How can we verify it:

Add a function (in my case it was a Rust function) that uses a non-node runtime and the app should still package correctly.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you rebase against the master? Thanks!

**Comment by j0k3r** [comment]
Also, could you add some tests to cover your changes?

File: lib/validate.js [hunk 1]
```diff
@@ -191,7 +191,10 @@ module.exports = {
       if (_.has(this.serverless, 'service.package') && this.serverless.service.package.individually) {
         this.multiCompile = true;
         this.serializedCompile = this.configuration.serializedCompile;
-        this.options.verbose && this.serverless.cli.log(`Using ${this.serializedCompile ? 'serialized' : 'multi'}-compile (individual packaging)`);
+        this.options.verbose &&
+          this.serverless.cli.log(
+            `Using ${this.serializedCompile ? 'serialized' : 'multi'}-compile (individual packaging)`
+          );
```
Comment (j0k3r) [inline lib/validate.js:197]: Was it required by the linter?

**Review by j0k3r — COMMENTED** [review]
Could you add a test to cover that update? Thanks 🙏

File: lib/validate.js (hunk 1 above)
Comment (jgrantr) [reply lib/validate.js:197]: Yes, in fact it made that change for me when I was trying to check it in. Must be a pre-commit hook or something.

**Comment by jgrantr** [comment]
> Could you add a test to cover that update? Thanks 🙏

Yes, I've been looking at the unit tests to figure out where to put it and what to check (as I would have expected the existing unit tests to fail, but they aren't). I think I've got that figured out, so I will try and get that in today.

**Comment by jgrantr** [comment]
Ok, I added a new function to the testFunctionsConfig. Without my fix in there, I get five failures. With my fix, all the tests pass.
Screen Shot 2021-02-02 at 2 46 03 PM

**Review by j0k3r — APPROVED** [review]
Great, thanks!
