### PR TITLE
Default entry individually

### LINKED ISSUE #272: Throw error when webpack entry is configured and package individually is true
# This is a Feature Proposal

## Description

Context: When package individually is set to true, webpack entry should not be configured at all. This is currently the expected behaviour. It is however not explicit enough to the plugin user and it will fail with some other error.

Proposal: Throw an error when webpack entry is configured and package individually is set to true. 

Related to:
* #266. See discussion [here](https://github.com/serverless-heaven/serverless-webpack/issues/266#issuecomment-341892898).

## Additional Data

* ***Serverless-Webpack Version you're using***:
3.1.2

* ***Webpack version you're using***:
3.5.5

* ***Serverless Framework Version you're using***:
1.23.0

* ***Operating System***:
OS X 10.10.5

* ***Stack Trace (if available)***:
```
Type error:

  Type Error ---------------------------------------------

  Path must be a string. Received [ 'babel-polyfill',
  'source-map-support/register',
  './packages/core/src/alexa-skill.js' ]

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.


Stack trace:
  Stack Trace --------------------------------------------

TypeError: Path must be a string. Received [ 'babel-polyfill',
  'source-map-support/register',
  './packages/core/src/alexa-skill.js' ]
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1248:5)
    at entryFunctions._.flatMap (/Users/ceilfors/github/realtime-ww2-alexa/node_modules/serverless-webpack/lib/validate.js:154:28)
    at /Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:3554:27
    at /Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:3001:24)
    at /Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:4913:18
    at baseMap (/Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:3553:7)
    at map (/Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:9571:14)
    at Function.flatMap (/Users/ceilfors/github/realtime-ww2-alexa/node_modules/lodash/lodash.js:9274:26)
    at ServerlessWebpack.validate (/Users/ceilfors/github/realtime-ww2-alexa/node_modules/serverless-webpack/lib/validate.js:153:31)
From previous event:
    at PluginManager.invoke (/Users/ceilfors/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/Users/ceilfors/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/Users/ceilfors/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/ceilfors/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/ceilfors/.nvm/versions/node/v8.1.2/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by ceilfors**
## What did you implement:

Closes #272.

Mainly:
- Default webpackConfig entry to lib.entries if package.individually is set to true.
- Throw error if entry is set to anything else other than empty value or lib.entries.

## How did you implement it:

Trivial change.

## How can we verify it:

New behaviour can be seen in the unit tests.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO (Do assess)

### CODE REVIEW

File: lib/validate.js [hunk 1]
```diff
@@ -135,13 +142,19 @@ module.exports = {
       this.options.verbose && this.serverless.cli.log('Using multi-compile (individual packaging)');
       this.multiCompile = true;
 
+      if (this.webpackConfig.entry && !_.isEqual(this.webpackConfig.entry, entries)) {
+        throw new this.serverless.classes
```
Comment (HyperBrain) [inline lib/validate.js]: We should reject here instead of throwing (`return BbPromise.reject(...)`). Validate is expected to return a promise. Imo mixing exceptions and promises is not very clean. BTW: I know that this is also done in Serverless and maybe there are some remnants in this plugin too ;-)

In the unit test you should then just use `expect(validate()).to.be.rejectedWith(/.../)`

**Comment by HyperBrain** [comment]
@serverless-heaven/serverless-webpack-contributors This change is very useful, because individual packaging does not work without using `slsw.lib.entries`, so it shows an error before the compilation starts.
Imo we can treat this as non-breaking change.
What is your opinion here?

**Comment by ceilfors** [comment]
Is there a way to retrigger the travis build? I'm just wondering if the travis failure is a flaky test or not as it's not failing in my local machine.

**Comment by HyperBrain** [comment]
Yes, saw it. Just push a dummy commit to trigger a rebuild. I'll check it
tomorrow.

Wisen Tanasa <notifications@github.com> schrieb am Sa., 11. Nov. 2017, 6:16
nachm.:

**Comment by ceilfors** [comment]
Thanks for the update. Is there anything else I can help with the merge?

**Comment by HyperBrain** [comment]
I'll merge it now ;-)
